export const ADD_DIARY = 'ADD_DIARY';
export const GET_DIARIES = 'GET_DIARIES';
export const DELETE_DIARY = 'DELETE_DIARY';
export const DIARY_LOADING = 'DIARY_LOADING';
export const FETCH_DIARY_SUCCESS = "FETCH_DIARY_SUCCESS";
export const DELETE_DIARY_SUCCESS = "DELETE_DIARY_SUCCESS";